server:
    port: 2612
spring:
    application:
        name: PhoneStore
    datasource:
        password: sa
        url: jdbc:sqlserver://localhost:1433;databaseName=PhoneShop;encrypt=true;trustServerCertificate=true
        username: sa
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.SQLServerDialect
