server:
    port: 8080
#logging:
#    level:
#        org.hibernate: DEBUG
spring:
    aop:
        auto: true
        proxy-target-class: true
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        mode: HTML5
        cache: false
    application:
        name: PhoneStore
    datasource:
        url: jdbc:sqlserver://localhost:1433;databaseName=PhoneStore;encrypt=true;trustServerCertificate=true
        username: sa
        password: 1
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jpa:
        database-platform: org.hibernate.dialect.SQLServerDialect
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            ddl-auto: update
        show-sql: true
    mail:
        host: smtp.gmail.com
        port: 587
        username: sieunhantanh2003@gmail.com
        password: eqik fdhn ytoo cxfq
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true