
server:
    port: 8080
    servlet:
        context-path: /
        session:
            persistent: true
            tracking-modes: cookie
            timeout: 15m
#logging:
#    level:
#        org.hibernate: DEBUG
spring:
    session:
        store-type: jdbc
    aop:
        auto: true
        proxy-target-class: true
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        mode: HTML5
        cache: false
        resources:
            static-locations: classpath:/static/, classpath:/public/, file:\static\img\ProductImg
    application:
        name: PhoneStore
    datasource:
        url: jdbc:sqlserver://localhost:1433;databaseName=PhoneStore;encrypt=true;trustServerCertificate=true;characterEncoding=utf8mb4
        username: sa
        password: 1
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jpa:
        database-platform: org.hibernate.dialect.SQLServerDialect
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            ddl-auto: none
        show-sql: true
    mail:
        host: smtp.gmail.com
        port: 587
        username: sieunhantanh2003@gmail.com
        password: eqik fdhn ytoo cxfq
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    servlet:
        multipart:
            enabled: true
            max-file-size: 100MB
            max-request-size: 100MB
    security:
        user:
            name: hung
            password: 1