server:
  port: 8080
  servlet:
    context-path: /

spring:
  aop:
    auto: true
    proxy-target-class: true
  application:
    name: PhoneStore
    availability:
      enabled: true
  datasource:
    url: "jdbc:sqlserver://localhost:1433;databaseName=PhoneStore;encrypt=true;trustServerCertificate=true;"
    driver-class-name: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
    username: sa
    password: 1  # Thay your_password_here bằng mật khẩu thực tế của bạn
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: false
#  web:
#    resources:
#      static-locations: classpath:/static/
#debug: true
#logging:
#  file:
#    name: logs/spring-boot-app.log
#  level:
#    root: INFO
#    org.springframework.web: DEBUG
#    org.thymeleaf: DEBUG